name: End-to-End Tests

on: [push, pull_request]

jobs:
  e2eTests:
    runs-on: ubuntu-latest
    services:
      kusto:
        image: ghcr.io/csharp-opensource/csharp.opensource.linqtokql-demo-cluster:master
        ports:
          - 8080:8080
    name: End-to-End Tests
    steps:
    - name: Verify Server is running
      run: curl -sS http://localhost:8080/health

    - uses: actions/setup-dotnet@v4
    
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set E2E_TESTING environment variables 
      run: echo "E2E_TESTING=1" >> $GITHUB_ENV

    - name: Restore
      run: dotnet restore ./LinqToKql.Test

    - name: Build
      run: dotnet build -clp:ErrorsOnly --no-restore ./LinqToKql.Test

    - name: Run unit tests
      run: dotnet test --no-restore --no-build ./LinqToKql.Test
