name: End-to-End Tests

on: [push, pull_request]

jobs:
  e2eTests:
    runs-on: ubuntu-latest
    name: End-to-End Tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Start local Kusto cluster
      working-directory: ./DemoCluster
      run: |
         docker build -t kusto . && docker rm -f kusto && docker run -it --name kusto -p 8080:8080 kusto

    - name: Set E2E_TESTING environment variables 
      run: echo "E2E_TESTING=1" >> $GITHUB_ENV

    - name: Restore
      run: dotnet restore ./LinqToKql.Test

    - name: Build
      run: dotnet build -clp:ErrorsOnly --no-restore ./LinqToKql.Test

    - name: Run unit tests
      run: dotnet test --no-restore --no-build ./LinqToKql.Test
