name: Unit Tests

on: [push, pull_request]

jobs:
  UnitTests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Restore
      run: dotnet restore ./LinqToKql.Test

    - name: Build
      run: dotnet build -clp:ErrorsOnly --no-restore ./LinqToKql.Test

    - name: Run unit tests
      run: dotnet test --no-restore --no-build ./LinqToKql.Test
